### ISSUE TITLE
Generate MAG L1A data

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#107]
### Summary

Create processing code which will convert MAG packets to Level 1a CDF files. 

### Requirements

The more specific the better.
  - [x] Parse packets using space_packet_parser
  - [x] Create XArray following the standard format for CDFs (#77 )
  - [x] Output CDF files for MAG L1A RAW BM/NM
  - [x] Apply processing steps in Algorithm document
  - [x] Output CDF files for MAG L1A MAGO/MAGI BM/NM
  - [x] Create a basic unit test for checking if packet decommutation works 

### Tickets
- #395 
- #349 
- #636 
- #801 
- #265 
- #1006
