### ISSUE TITLE
Spin and Repoint Database

### ISSUE THREAD

**Issue by tech3371** [IMAP-Science-Operations-Center/imap_processing#1127]
- [ ] IMAP-Science-Operations-Center/sds-data-manager#384
- [ ] IMAP-Science-Operations-Center/sds-data-manager#392
- [ ] IMAP-Science-Operations-Center/sds-data-manager#385
- [ ] IMAP-Science-Operations-Center/sds-data-manager#386
- [ ] IMAP-Science-Operations-Center/sds-data-manager#402
- [ ] IMAP-Science-Operations-Center/sds-data-manager#387
- [ ] IMAP-Science-Operations-Center/imap_processing#1132
- [ ] IMAP-Science-Operations-Center/imap_processing#1133

**Comment by tech3371** [comment]
I believe this is done now given that sub tickets being completed.
