### ISSUE TITLE
[L5] Setup Access to Ancillary data

### ISSUE THREAD

**Issue by sdhoyt** [IMAP-Science-Operations-Center/imap_processing#120]
### Summary of the L5 requirement

Create EFS, add files to EFS, and setup batch job and lambda access for SPICE files. 

### Parent requirement

SOC-SDC-L4-29 | SDC Execution of L1 Processing Software | The SDC shall be capable of executing L1 processing software to produce L1 data products within seven (7) days of receipt of all requisite data inputs. | Requirement | The SDC produces L1 data products via Instrument Team supplied algorithms and SDC produced processing code. | SOC-L3-57 | Test | SIT-3: L0 -> L1 processing | SIT-3
-- | -- | -- | -- | -- | -- | -- | -- | --

### Tasks

- [x] Create EFS
- [x] Setup batch job access
- [x] Setup lambda access
- [x] Setup SPICE symlink for latest version
