### ISSUE TITLE
[L5] Create Template Docker code

### ISSUE THREAD

**Issue by laspsandoval** [IMAP-Science-Operations-Center/imap_processing#239]
### Summary

Template docker code for science data processing needs to be created. This template will be used by all instruments (instrument specific modifications will be needed, but these are not part of this ticket) for all data processing levels. The template will include access to resources such as the APIs, EFS, and Universal Spin Table. Creation of those resources is done in the [Setup Access to Ancillary data ticket](https://github.com/IMAP-Science-Operations-Center/imap_processing/issues/120).

<!DOCTYPE html><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; caret-color: rgb(230, 237, 243); color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Parent requirement</h3>

SOC-SDC-L4-29 | SDC Execution of L1 Processing Software | The SDC shall be capable of executing L1 processing software to produce L1 data products within seven (7) days of receipt of all requisite data inputs. | Requirement | The SDC produces L1 data products via Instrument Team supplied algorithms and SDC produced processing code. | SOC-L3-57 | Test | SIT-3: L0 -> L1 processing | SIT-3
-- | -- | -- | -- | -- | -- | -- | -- | --

### Requirements

  - Modify imap_python_processing_example
  - Include apis for downloading/uploading/querying data in s3
  - Ability to access EFS (most recent SPICE kernels using simlinks)
  - Access to Universal Spin table (may do this later since we don't have it yet)
  - Test to make certain it will run in Batch job. 
  - Consider what arguments and env variables will be passed to container.

### Tasks

- [ ] IMAP-Science-Operations-Center/imap_processing#240
- [ ] IMAP-Science-Operations-Center/imap_processing#241
- [ ] IMAP-Science-Operations-Center/imap_processing#242
- [ ] IMAP-Science-Operations-Center/imap_processing#243
