### ISSUE TITLE
Validate CoDICE L1A CDFs

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#251]
- [x] #1192 

CDFs to validate:

- [x] `hskp`
- [x] `lo-counters-aggregated`
- [x] `lo-counters-singles`
- [x] `hi-counters-aggregated`
- [x] `hi-counters-singles`
- [x] `hi-priorities`
- [x] `lo-sw-priority`
- [x] `lo-nsw-priority`
- [x] `lo-sw-angular`
- [x] `lo-nsw-angular`
- [x] `lo-sw-species`
- [x] `lo-nsw-species`
- [x] `lo-pha`
- [x] `hi-pha`
- [x] `hi-omni`
- [x] `hi-sectored`
- [x] `lo-ialirt`
- [ ] `hi-ialirt`
