### ISSUE TITLE
Produce CoDICE L1B CDFs

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#405]
- [ ] Convert data arrays to rates for CoDICE-lo
- [ ] Convert data arrays to rates for CoDICE-hi
- [ ] Convert data arrays to rates for Event Data
- [ ] Convert data arrays to rates for i-alirt Data
