### ISSUE TITLE
Validate CoDICE L1B CDFs

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#406]
CDFs to validate:

- [ ] `hskp`
- [ ] `lo-counters-aggregated`
- [ ] `lo-counters-singles`
- [ ] `hi-counters-aggregated`
- [ ] `hi-counters-singles`
- [ ] `hi-priorities`
- [ ] `lo-sw-priority`
- [ ] `lo-nsw-priority`
- [ ] `lo-sw-angular`
- [ ] `lo-nsw-angular`
- [ ] `lo-sw-species`
- [ ] `lo-nsw-species`
- [ ] `lo-pha`
- [ ] `hi-pha`
- [ ] `hi-omni`
- [ ] `hi-sectored`
- [ ] `lo-ialirt`
- [ ] `hi-ialirt`
