### ISSUE TITLE
HIT L0 Science Packet Decom

### ISSUE THREAD

**Issue by vmartinez-cu** [IMAP-Science-Operations-Center/imap_processing#699]

**Comment by vmartinez-cu** [comment]
After brainstorming more on how to handle data spread across multiple packets, it may not make sense to use data classes anymore. Need to think about this some.

Need to modify TLM differently than initially planned. Put all science data in one row as BYTE data type. This will require more decom work in the code.

- [x] Use result from Greg's packet_file_to_datasets function as input. (dictionary with apids as keys and data in xarray format) (issue #822 )
- [x] Group packets into groups of 20 to create science frames. Use group flag and sequence counts to assemble the frames. (issue #820 )
- [x] Parse binary counts data and organize data into data variables (EVRATES, SNGRATES, etc.). Event data do not need to be decommutated. (issue #821 )
- [x] Decompress science data. Event data do not require decompression (issue #1055)
