### ISSUE TITLE
Produce CoDICE L2 CDFs

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#873]
- [ ] Implement Lo Species Intensities processing
- [ ] Implement Lo Angular Intensities processing
- [ ] Implement Hi Omni-directional Intensities processing
- [ ] Implement Lo Sectored Intensities processing
