### ISSUE TITLE
Validate CoDICE L2 CDFs

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap_processing#874]
- [ ] Validate Lo Species Intensities data product
- [ ] Validate Lo Angular Intensities data product
- [ ] Validate Hi Omni-directional Intensities data product
- [ ] Validate Lo Sectored Intensities data product

**Comment by tech3371** [comment]
I am going to close this old tickets for CoDICE as well.
