### ISSUE TITLE
Produce GLOWS L1B CDFs

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#896]
# Steps
- [ ] Produce DE CDFs
- [ ] Produce Histogram CDFs
- [x] Transform L1A data to L1B data
- [x] Create L1B attributes
- [x] Create validation tests

# Tickets
- #201 
- #895
- #897 
- #918 
- #998

**Comment by maxinelasp** [comment]
Remaining work is blocked by lacking SPICE tools, see #897
