### ISSUE TITLE
Produce GLOWS L2 CDFs

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap_processing#899]
# Steps
- [ ] Produce Histogram L2 CDFs
- [ ] Generate CDF attributes
- [ ] Add validation testing

# Tasks
- #916 
- #917
